// <auto-generated />
using FrogBot.Voting;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FrogBot.Migrations
{
    [DbContext(typeof(VoteDbContext))]
    [Migration("20210826021103_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("FrogBot.Voting.Vote", b =>
                {
                    b.Property<ulong>("ChannelId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("MessageId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("ReceiverId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("VoterId")
                        .HasColumnType("bigint unsigned");

                    b.Property<int>("VoteType")
                        .HasColumnType("int");

                    b.HasKey("ChannelId", "MessageId", "ReceiverId", "VoterId", "VoteType");

                    b.ToTable("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
